In [1]:
import numpy as np

In [2]:
T,H = 5,4
hs = np.random.randn(T,H)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02])

In [3]:
ar = a.reshape(5,1).repeat(4, axis=1)
print(ar)

[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]


In [4]:
print(hs)

[[ 1.06992892  0.62738399 -0.53252558 -0.60762027]
 [ 0.32112509 -0.82707874  0.84872165 -1.29333919]
 [ 0.6938465   0.93974623 -0.17513435 -0.17430116]
 [ 0.59237411  0.58243641 -0.31713789 -0.03758297]
 [-0.69728927  1.50770685 -1.38284813  1.27152078]]


In [6]:
t = hs * ar
print(t)

[[ 0.85594314  0.5019072  -0.42602046 -0.48609622]
 [ 0.03211251 -0.08270787  0.08487216 -0.12933392]
 [ 0.0208154   0.02819239 -0.00525403 -0.00522903]
 [ 0.02961871  0.02912182 -0.01585689 -0.00187915]
 [-0.01394579  0.03015414 -0.02765696  0.02543042]]


In [7]:
c = np.sum(t,axis=0)
print(c.shape)

(4,)


In [8]:
c

array([ 0.92454396,  0.50666767, -0.38991619, -0.5971079 ])