In [1]:
import numpy as np

## 重み付き和の実装

In [2]:
T,H = 5,4
hs = np.random.randn(T,H)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02])

In [3]:
ar = a.reshape(5,1).repeat(4, axis=1)
print(ar)

[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]


In [4]:
print(hs)

[[ 1.06992892  0.62738399 -0.53252558 -0.60762027]
 [ 0.32112509 -0.82707874  0.84872165 -1.29333919]
 [ 0.6938465   0.93974623 -0.17513435 -0.17430116]
 [ 0.59237411  0.58243641 -0.31713789 -0.03758297]
 [-0.69728927  1.50770685 -1.38284813  1.27152078]]


In [6]:
t = hs * ar
print(t)

[[ 0.85594314  0.5019072  -0.42602046 -0.48609622]
 [ 0.03211251 -0.08270787  0.08487216 -0.12933392]
 [ 0.0208154   0.02819239 -0.00525403 -0.00522903]
 [ 0.02961871  0.02912182 -0.01585689 -0.00187915]
 [-0.01394579  0.03015414 -0.02765696  0.02543042]]


In [7]:
c = np.sum(t,axis=0)
print(c.shape)

(4,)


In [8]:
c

array([ 0.92454396,  0.50666767, -0.38991619, -0.5971079 ])

## バッチ処理版の重み付き和の実装

In [10]:
N,T,H = 10,5,4
hs = np.random.randn(N,T,H)
a = np.random.randn(N, T)
ar = a.reshape(N, T, 1).repeat(H, axis=2)

In [13]:
t = hs * ar
print(t.shape)
print(t)

(10, 5, 4)
[[[-0.19025786 -0.11997848 -0.4957948  -1.59924724]
  [-0.26039053  0.11733221 -0.0269754  -0.01947011]
  [ 0.4219718  -0.44518118 -1.01047478 -1.16769086]
  [ 0.4841305  -0.38349248 -0.57181502  0.32332853]
  [ 0.60387006 -0.9004709   0.97014867  2.02644627]]

 [[-0.99564643  1.03087795  0.05290311 -0.10630611]
  [-0.42517884  0.05696828 -0.01838178 -0.76505821]
  [-3.00747041 -1.92982765 -2.63655472 -3.31525939]
  [-1.67526501 -0.61896389  0.45833206  0.67625585]
  [ 0.09674549  0.06729912 -0.03427757 -0.03994594]]

 [[-0.05503972  0.09711847 -0.11397793  0.24814371]
  [-0.23292985  0.07042208  0.23403724  0.597125  ]
  [ 1.98423667 -0.52499108  0.25916379  0.52784523]
  [-0.54476073 -1.39611787 -0.33992325  2.13439525]
  [-0.503456    0.73270677 -2.13531233  1.73765503]]

 [[-0.68977969  0.74586367 -0.14258513 -0.89123897]
  [ 0.33395245 -0.05838972 -0.40897456  0.11760739]
  [-0.18340476  0.23432085  0.13809048 -0.28498888]
  [-0.23868981  0.28637863 -0.25594758  0.27037

In [14]:
c = np.sum(t, axis=1)
print(c)
print(c.shape)

[[ 1.05932397 -1.73179083 -1.13491133 -0.43663342]
 [-6.0068152  -1.3936462  -2.17797891 -3.55031381]
 [ 0.64805037 -1.02086163 -2.09601248  5.24516422]
 [-0.6951742   1.2730926  -0.58822182 -0.88169682]
 [ 1.82256177 -1.52974077  0.05627837  0.5128269 ]
 [-0.79722362  2.56947175  0.406497    2.34372694]
 [ 2.20842362  2.77162879 -0.84333604 -1.23686647]
 [ 3.22719999  0.08898756  6.04932358  2.96105821]
 [-0.71780457  0.26838033 -1.13839857 -0.25848596]
 [ 2.31646871 -2.57952533  0.21455538 -1.56804985]]
(10, 4)
