In [1]:
import numpy as np

In [2]:
w1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)
h = np.dot(x,w1) + b1

In [6]:
def sigmoid(x):
    return 1 / (1/np.exp(-x))

In [8]:
x = np.random.randn(10,2)

w1 = np.random.randn(2,4)
b1 = np.random.randn(4)

w2 = np.random.randn(4,3)
b2 = np.random.randn(3)

h = np.dot(x,w1) + b1
a = sigmoid(h)
s = np.dot(a,w2) + b2
print(s)

[[  1.168241    -0.77938835  -1.33390699]
 [  8.83659212  -7.16838071  -2.32977084]
 [  5.06123992  -3.2985328   -4.1283273 ]
 [ 26.79394718 -20.4881297  -11.6496854 ]
 [ 13.71066385 -12.55828583  -4.19624008]
 [ 10.93940665  -8.35634306  -4.01811495]
 [  0.24475459  -0.25263145  -0.35365383]
 [ -0.78559167   0.64874589  -1.29408514]
 [  9.68382295  -7.38103367  -3.46359058]
 [  0.35748317  -0.37422414  -0.05209632]]
